In [3]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
n2=np.array([[10,20,30,40],[30,67,38,20]])
n2

array([[10, 20, 30, 40],
       [30, 67, 38, 20]])

### Numpy zeroes-

In [5]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [6]:
n4=np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
type(n4)

numpy.ndarray

### Numpy full-

In [8]:
n5=np.full((3,4),44)
n5

array([[44, 44, 44, 44],
       [44, 44, 44, 44],
       [44, 44, 44, 44]])

### Numpy arrange method-

In [9]:
n6=np.arange(10,15)
n6

array([10, 11, 12, 13, 14])

In [10]:
n7=np.arange(10,40,5)
n7

array([10, 15, 20, 25, 30, 35])

### Numpy random numbers-

In [11]:
n8=np.random.randint(1,1000,5)
n8

array([916, 797, 434, 834, 790])

### Numpy shape-

In [12]:
n2

array([[10, 20, 30, 40],
       [30, 67, 38, 20]])

In [13]:
n2.shape

(2, 4)

In [14]:
n2.shape= (4,2)

In [15]:
n2

array([[10, 20],
       [30, 40],
       [30, 67],
       [38, 20]])

### Joining numpy arrays-

In [16]:
nn1=np.array([1,3,6,5])
nn2=np.array([4,7,5,3])
np.vstack((nn1,nn2))

array([[1, 3, 6, 5],
       [4, 7, 5, 3]])

In [17]:
np.hstack((nn1,nn2))

array([1, 3, 6, 5, 4, 7, 5, 3])

In [18]:
np.column_stack((nn1,nn2))

array([[1, 4],
       [3, 7],
       [6, 5],
       [5, 3]])

### Numpy intersection and differences-

In [19]:
np.intersect1d(nn1,nn2)

array([3, 5])

In [20]:
np.setdiff1d(nn1,nn2)

array([1, 6])

In [21]:
np.setdiff1d(nn2,nn1)

array([4, 7])

### Numpy array addition-

In [22]:
np.sum([nn1,nn2])

34

In [23]:
np.sum([nn1,nn2],axis=0)

array([ 5, 10, 11,  8])

In [24]:
np.sum([nn1,nn2], axis=1)

array([15, 19])

### Numpy basic scalar operations-

In [25]:
nn3=np.array([2,5,8,10])
nn3=nn3+5
nn3

array([ 7, 10, 13, 15])

In [26]:
nn4=np.array([2,5,8,10])
nn4=nn4-1
nn4

array([1, 4, 7, 9])

In [27]:
nn5=np.array([2,5,8,10])
nn5=nn5/2
nn5

array([1. , 2.5, 4. , 5. ])

In [28]:
nn6=np.array([2,5,8,10])
nn6=nn6*2
nn6

array([ 4, 10, 16, 20])

### Numpy math function-

In [29]:
nn7=np.array([2,4,6,8,10,12,14])
np.mean(nn7)

8.0

In [30]:
np.median(nn7)

8.0

In [31]:
np.std(nn7)

4.0

### Numpy save and load-

In [33]:
nn8=np.random.randint(12,100,5)
nn8

array([75, 16, 63, 42, 37])

In [34]:
np.save('random_numpy', nn8)

In [36]:
nn9=np.load('random_numpy.npy')
nn9

array([75, 16, 63, 42, 37])